### PR TITLE
Revert "Add Hadoop LZO codec shim"

### PR DESCRIPTION
**Pull request by findepi**
Reverts trinodb/trino-hive-apache#22

The `com.hadoop.compression.lzo.LzoCodec` was conflicting on `trino-rcfile` test classpath, 
being pulled from here & `org.anarres.lzo:lzo-hadoop` dependency.

### CODE REVIEW

**Comment by losipiuk** [comment]
Another option would be to exclude conflicting file in `trino-rcfile`? Or are we afraid that conflicting class will also be present in prod environment, not only in our tests?

**Comment by electrum** [comment]
We don't need to revert here. Instead, we can completely remove `hadoop-lzo` from Trino. We need to make the `end()` calls a no-op in Aircompressor, but we can patch that here in `CodecPool` for testing:

```patch
diff --git a/src/main/java/org/apache/hadoop/hive/ql/io/CodecPool.java b/src/main/java/org/apache/hadoop/hive/ql/io/CodecPool.java
index fab76fc..7da5e64 100644
--- a/src/main/java/org/apache/hadoop/hive/ql/io/CodecPool.java
+++ b/src/main/java/org/apache/hadoop/hive/ql/io/CodecPool.java
@@ -37,11 +37,17 @@ public final class CodecPool
 
     public static void returnCompressor(Compressor compressor)
     {
-        compressor.end();
+        // TODO: fix this in Aircompressor
+        if (!compressor.getClass().getName().equals("io.airlift.compress.lzo.LzoCodec$HadoopLzoCompressor")) {
+            compressor.end();
+        }
     }
 
     public static void returnDecompressor(Decompressor decompressor)
     {
-        decompressor.end();
+        // TODO: fix this in Aircompressor
+        if (!decompressor.getClass().getName().equals("io.airlift.compress.lzo.LzoCodec$HadoopLzoDecompressor")) {
+            decompressor.end();
+        }
     }
 }
```

With that, I'm able to run `TestRcFileReader` using the below. I changed `quickTestRcFileReader()` to `LZO` for local testing purposes. However, it's normally not used at all, even in `fullTestRcFileReader()`.

```patch
diff --git a/lib/trino-parquet/pom.xml b/lib/trino-parquet/pom.xml
index 21e577f9d4..b8945376bc 100644
--- a/lib/trino-parquet/pom.xml
+++ b/lib/trino-parquet/pom.xml
@@ -146,6 +145,0 @@
-        <dependency>
-            <groupId>org.anarres.lzo</groupId>
-            <artifactId>lzo-hadoop</artifactId>
-            <scope>test</scope>
-        </dependency>
-
diff --git a/lib/trino-rcfile/pom.xml b/lib/trino-rcfile/pom.xml
index 067abecdcd..9d033ca76e 100644
--- a/lib/trino-rcfile/pom.xml
+++ b/lib/trino-rcfile/pom.xml
@@ -106,6 +105,0 @@
-        <dependency>
-            <groupId>org.anarres.lzo</groupId>
-            <artifactId>lzo-hadoop</artifactId>
-            <scope>test</scope>
-        </dependency>
-
diff --git a/lib/trino-rcfile/src/test/java/io/trino/rcfile/RcFileTester.java b/lib/trino-rcfile/src/test/java/io/trino/rcfile/RcFileTester.java
index 61b033cf12..0753d8171d 100644
--- a/lib/trino-rcfile/src/test/java/io/trino/rcfile/RcFileTester.java
+++ b/lib/trino-rcfile/src/test/java/io/trino/rcfile/RcFileTester.java
@@ -130,0 +131 @@ import static io.trino.rcfile.RcFileTester.Compression.LZ4;
+import static io.trino.rcfile.RcFileTester.Compression.LZO;
@@ -132 +132,0 @@ import static io.trino.rcfile.RcFileTester.Compression.NONE;
-import static io.trino.rcfile.RcFileTester.Compression.SNAPPY;
@@ -300 +300 @@ public class RcFileTester
-        rcFileTester.compressions = ImmutableSet.of(SNAPPY);
+        rcFileTester.compressions = ImmutableSet.of(LZO);
diff --git a/plugin/trino-hive/pom.xml b/plugin/trino-hive/pom.xml
index 4229f93ef0..7cbde82dc5 100644
--- a/plugin/trino-hive/pom.xml
+++ b/plugin/trino-hive/pom.xml
@@ -358,6 +357,0 @@
-        <dependency>
-            <groupId>org.anarres.lzo</groupId>
-            <artifactId>lzo-hadoop</artifactId>
-            <scope>test</scope>
-        </dependency>
-
diff --git a/pom.xml b/pom.xml
index a3ff38ec2d..2494bf6b4d 100644
--- a/pom.xml
+++ b/pom.xml
@@ -537 +537 @@
-                <version>3.1.2-6</version>
+                <version>3.1.2-8-SNAPSHOT</version>
```

**Comment by electrum** [comment]
Here's the fix to Aircompressor: https://github.com/airlift/aircompressor/pull/120

**Comment by findepi** [comment]
@electrum i am not sure i understand the proposal.
i hope the `hadoop-lzo` test dependency is used for testing compatibility for rcfile.

i would be considered about losing test coverage if we stop using `hadoop-lzo` there.
Perhaps, we could make the test into a product test instead?

Anyway, is there any significant problem with my current approach?

**Comment by electrum** [comment]
It’s actually not used at all, as I said, since that enum value is never referenced. A product test is better anyway, since that tests data written by Hive.

Having the foreign package here is cleaner than putting it in the main code base.

**Comment by findepi** [comment]
> It’s actually not used at all

i was sure i checked that, but apparently i must have checked it wrong

**Pull request closed without merging**
