### PR TITLE
Upgrade to parquet 1.12.0

### PR DESCRIPTION
**Pull request by raunaqmorarka**

### CODE REVIEW

**Comment by raunaqmorarka** [comment]
@electrum 
Somehow I don't see the option to "request review" like in the trinodb repo

**Comment by electrum** [comment]
This pulls in `com.github.luben:zstd-jni` which we don't want. Need to investigate.

**Comment by electrum** [comment]
This should fix it:
```patch
diff --git a/pom.xml b/pom.xml
index 78865a3..d71bfc1 100644
--- a/pom.xml
+++ b/pom.xml
@@ -474,6 +474,10 @@
             <artifactId>parquet-hadoop</artifactId>
             <version>${dep.parquet.version}</version>
             <exclusions>
+                <exclusion>
+                    <groupId>com.github.luben</groupId>
+                    <artifactId>zstd-jni</artifactId>
+                </exclusion>
                 <exclusion>
                     <groupId>org.xerial.snappy</groupId>
                     <artifactId>snappy-java</artifactId>
```

**Comment by raunaqmorarka** [comment]
> This should fix it:
> 

Thanks, made that change now

**Comment by electrum** [comment]
We're going to need to fork `org.apache.parquet.hadoop.metadata.CompressionCodecName` to use Aircompressor classes for all of these, since the native code is not available (and we don't want to use it).

**Comment by electrum** [comment]
You can install a snapshot of this locally and run `TestFullParquetReader` to verify that the compression codecs work. Maybe modify `fullParquetTester()` to include `LZ4` and `LZO` in `writerCompressions` -- not sure why those are not included now.

**Comment by electrum** [comment]
This will be non-trivial since Parquet has some custom stuff (e.g., their `SnappyCodec`) and we should do it for all of the codecs, so we can do that as a separate project. For now, add the dependency to the shading `<excludes>` list so that it becomes a normal dependency.

**Review by electrum — APPROVED** [review]

**Pull request merged**
