### PR TITLE
Update to Parquet 1.11.1

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Review by martint — APPROVED** [review]

**Comment by findepi** [comment]
https://github.com/trinodb/trino/pull/6514#issuecomment-754950218 :)

**Comment by martint** [comment]
> [trinodb/trino#6514 (comment)](https://github.com/trinodb/trino/pull/6514#issuecomment-754950218) :)

Indeed 🙂

**Comment by electrum** [comment]
I can't remember, which is a good reason to explain why. Maybe it was motivated by the [Iceberg update](https://github.com/apache/iceberg/issues/1441).

The Hive JAR is ~19MB smaller due to [PARQUET-1853](https://issues.apache.org/jira/browse/PARQUET-1853), so maybe that's reason enough?

**Comment by kosinsky** [comment]
1.11.1 fixes compatibility with Apache Arrow: https://issues.apache.org/jira/browse/PARQUET-1879 as well as with Spark https://issues.apache.org/jira/browse/PARQUET-1739

**Comment by electrum** [comment]
There were issues when I ran the Hive tests against a snapshot version of this PR. IIRC, some missing fastutil classes in the Parquet shading. This requires more investigation before merging.

**Pull request merged**
